services:
  live-recorder:
    build: .
    container_name: live_recorder
    ports:
      - "${DB_EXPOSE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: live_recorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./downloads:/app/downloads
    restart: always
